config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do #change from clearance for mailer
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => 'welcome#index', as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  post "/developers/:id/show2" => "developers#show2"
  
  

  resources :projects do
    member do
      get "like", to: "projects#upvote"
      get "dislike", to: "projects#downvote"
    end
  end
  
  root 'welcome#index'
  resources :developers
  resources :projects
  post "/"    => "users#create"
  get '/list' => "projects#list"
  get '/list2' => "projects#list2"
  get 'projshow' => 'projects#show_proj'
  get "/add_dev" => 'projects#add_dev'
  get '/add_dev_leave' => 'projects#add_dev_leave'
  get '/show3' => 'developers#show3'
  get '/add_dev_leave1' => 'projects#add_dev_leave1'
  get "/add_dev1" => 'projects#add_dev1'
  

end

app/models/developer.rb
class Developer < ActiveRecord::Base

  belongs_to :users
  has_many :projects

  mount_uploader :avatar, AvatarUploader  
  
  acts_as_votable

  validates :name, presence: true 
  validates :skills, presence: true
  validates :motto, presence: true    

end

app/controllers/developers_controller.rb
class DevelopersController < ApplicationController

  def index
    @developer = Developer.where.not(users_id: current_user[:id])
  end

  def create
    

    if params[:developer][:skills].length > 0
      b = params[:developer][:skills].split(', ')
    else
      b = []
    end
    {'ruby' => params[:developer][:ruby], 'Python' => params[:developer][:Python], 'JavaScript' => params[:developer][:JavaScript],'JScript' => params[:developer][:JScript], 'C' => params[:developer][:C], "C++" => params[:developer][:"C++"],"C#" =>  params[:developer][:"C#"], "Objective-C" => params[:developer][:"Objective-C"], "Digital Marketing" => params[:developer][:"Digital Marketing"], "PHP" => params[:developer][:PHP], "SQL" => params[:developer][:SQL], "Bash" => params[:developer][:Bash], "Swift" => params[:developer][:Swift]}.each_pair do |key,value|
      
      if value == "1" 
        b << key
      else
      end
    end
	 a = Developer.new(name: params[:developer][:name], description: params[:developer][:description], motto: params[:developer][:motto], avatar: params[:developer][:avatar], skills: b, users_id: current_user[:id])

   
	 if a.save 
    
	  redirect_to root_path
	 else
    
 	  redirect_to root_path
	 end
  end

  def show
    a = Developer.find_by(users_id: current_user[:id])
    render :json => a
  end

  def show2
   a = Developer.find(params[:id])
   a.avatar = params[:developer][:avatar]
   a.save
    redirect_to root_path, flash: {notice: "bla"}
  end

  def show3
    a = Developer.find(params['id'])
    render :json => a
  end

  def update
    if params.first[0] == 'skills'
      a = Developer.find(params['id'])
      a.skills << params.first[1]
      a.save
      render :json => ["ok"]
    elsif params.first[0] == 'killskill'
      a = Developer.find(params['id'])
      a.skills.delete("#{params.first[1]}")
      if a.save
        render :json => ["ok"]
      else
        render :json => ["no"]
      end
    else
      Developer.update(params['id'], params.first[0] => params.first[1])
      render :json => ["ok"]
    end
  end
 
  def destroy
    a = Developer.find_by(users_id: current_user[:id])
    a.destroy
    redirect_to root_path
  end
 
  private
 
  def developer_params
    params.permit(:name, :description, :motto, :avatar, :skills, :ruby, :Python, :JavaScript, :JScript, :C, :"C++", :"C#", :"Objective-C", :"Digital Marketing", :PHP, :SQL, :Bash, :Swift)
  end

end

app/helpers/developers_helper.rb
module DevelopersHelper
end

app/views/developers/_bla.html.erb
<%=form_for :developer, url: '/developers', method: :patch do |f| %>
	
		<%= f.file_field :avatar, class: "form-control" %>
	
    	<%= f.submit "Submit", class: "btn btn-primary, col-sm-12" %>
  	
<% end %>

app/views/developers/_form.html.erb
      
      <div class="modal-body">

<%=form_for :developer, url: '/developers', method: :post do |f| %>
	<div>
		<%= f.label :name %>
		<%= f.text_field :name, class: "form-control" %>
	</div>
	<br>

	<div>
		<%= f.label :skills %>
		<%= f.text_field :skills, placeholder: "Ruby, Python, Java Script, Objective C, etc...", class: "form-control" %>
	</div>

	<div>
      <%= f.check_box :ruby, class: "checkbox1", bla: "Ruby"%> Ruby
 	  <%= f.check_box :Python, class: "checkbox1", bla: "Python"%> Python
      <%= f.check_box :JavaScript, class: "checkbox1", bla: "JavaScript"%> JavaScript
      <%= f.check_box :JScript, class: "checkbox1", bla: "JScript"%> JScript
 	  <%= f.check_box :C, class: "checkbox1", bla: "C"%> C
 	  <%= f.check_box :"C++", class: "checkbox1", bla: "C++"%> C++
 	  <%= f.check_box :"C#", class: "checkbox1", bla: "C#"%> C#
 	  <%= f.check_box :"Objective-C", class: "checkbox1", bla: "Objective-C"%> Objective-C
 	  <%= f.check_box :"Digital Marketing", class: "checkbox1", bla: "Digital Marketing"%> Digital Marketing
 	  <%= f.check_box :PHP, class: "checkbox1", bla: "PHP"%> PHP
	  <%= f.check_box :SQL, class: "checkbox1", bla: "SQL"%> SQL
 	  <%= f.check_box :Bash, class: "checkbox1", bla: "Bash"%> Bash
 	  <%= f.check_box :Swift, class: "checkbox1", bla: "Swift"%> Swift
  	</div>

	<br>
	
	<div>
		<%= f.label :description %>
		<%= f.text_area :description, placeholder: "Portfolio", class: "form-control" %>
	</div>
	<br>

	<div>
		<%= f.label :motto %>
		<%= f.text_field :motto, placeholder: "One sentence that describe who you are.", class: "form-control" %>
	</div>
	<br>

	<div>
		<%= f.label :avatar %>
		<%= f.file_field :avatar, class: "form-control" %>
	</div>
	<br>


	<br>
    <div>
    	<%= f.submit "Submit", class: "btn btn-primary, col-sm-12" %>
 	  <!-- <a href="" class="btn btn-primary, col-sm-12" id="newdevbtn">Submit</a>		 -->
  	</div>
<% end %>
</div>

app/views/developers/edit.html.erb
<%= render "developers/form" %>

app/views/developers/index.html.erb
<!-- NAV BAR  -->
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="http://localhost:3000/"><img src="/Logo/logo1.png"/></a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user != nil %>
          <li><a href="#">Log in as: <%= current_user.email %></a></li>
        <% end %>
        <li><%= link_to "sign out", sign_out_path, method: :delete %></li>
       
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<!-- end of navbar -->

<% a = 0 %>
<%@developer.each_with_index do |x, indx| %>
	<% if a == 0 %>
		<% if indx.even? %>
			<div class="bla">
				<div class="story">
					<div class="float-left">
						<table class="table-box-developer" style="width:100%;">
						<tr>
							<td class="td-name"><h1><%= x.name %></h1></td>
							<td></td>
							<td class="td-avatar"><img src="<%= x.avatar %>" style="border-radius: 20px; width: 120px; height: 120px;"></td>
						</tr>
						</table>
						<br>
						<h3>"<%= x.motto %>"</h3>
						<br>
						<h5>Skills: </h5>
						<% x.skills.each do |y| %>
							<%= y%>
							<br>
						<%end%>
						<br>
						<div class="description" style="display: none;"><h5>Portfolio: </h5><%=x.description%><br>

						<a href="javascript:min_proj_list(<%=x.id%>)" bla='<%=x.id%>' class="join">Invite this person to my project</a>

						<a href="" class="hide_desrcipt"> | Hide this</a>
						  <%= link_to like_project_path(x), class: "upvote", method: 'get', remote: true do %>
	     				  <button type="button" class="btn btn-info" aria-label="Left Align">
	       				  <span class="glyphicon glyphicon-thumbs-up glyphicon-align-center" aria-hidden="true"></span>
	       				  <span class="upbadge"><%= x.get_upvotes.size %></span>
	     				  </button>
	     			  <% end %>  
						  <%= link_to dislike_project_path(x), class: "downvote", method: 'get', remote: true do %>
	     				  <button type="button" class="btn btn-info" aria-label="Left Align">
								  <span class="glyphicon glyphicon-thumbs-down glyphicon-align-center" aria-hidden="true"></span>
								  <span class="downbadge"><%= x.get_downvotes.size %></span>
							  </button>
	   				  <% end %></div>
						<a href="" class="show_more_btn">Show more >></a>
					</div>
				</div>
			</div>
			<% indx+=1 %>
			<% if indx == @developer.size %>
				<div class="bla" style="background: url(/1.jpg) 50% 0 repeat;">
			<% end %>
		<% else %>
			<div class="bla1" style="background: url(/2.jpg) 50% 0 repeat fixed;">
				<div class="story">
					<div class="float-right">
						<table class="table-box-developer" style="width:100%;">
						<tr>
							<td class="td-name"><h1><%= x.name %></h1></td>
							<td></td>
							<td class="td-avatar"><img src="<%= x.avatar %>" style="border-radius: 20px; width: 120px; height: 120px;"></td>
						</tr>
						</table>
						<br>
						<h3>"<%= x.motto %>"</h3>
						<br>
						<h5>Skills: </h5>
						<% x.skills.each do |y| %>
							<%= y%>
							<br>
						<%end%>
						<br>
						<div class="description" style="display: none;"><h5>Portfolio: </h5><%=x.description%><br>

						<a href="javascript:min_proj_list(<%=x.id%>)" class="join" bla='<%=x.id%>'>Invite this person to my project</a>

						<a href="" class="hide_desrcipt"> | Hide this</a>
						  <%= link_to like_project_path(x), class: "upvote", method: 'get', remote: true do %>
	     				  <button type="button" class="btn btn-info" aria-label="Left Align">
	       				  <span class="glyphicon glyphicon-thumbs-up glyphicon-align-center" aria-hidden="true"></span>
	       				  <span class="upbadge"><%= x.get_upvotes.size %></span>
	     				  </button>
	     			  <% end %> 
						  <%= link_to dislike_project_path(x), class: "downvote", method: 'get', remote: true do %>
	     				  <button type="button" class="btn btn-info" aria-label="Left Align">
								  <span class="glyphicon glyphicon-thumbs-down glyphicon-align-center" aria-hidden="true"></span>
								  <span class="downbadge"><%= x.get_downvotes.size %></span>
							  </button> <% end %>
							  </div>  
						<a href="" class="show_more_btn">Show more >></a>
					</div>
				</div>
			</div>
			<% indx+=1 %>
			<% if indx == @developer.size %>
				<div class="bla" style="background: url(/1.jpg) 50% 0 repeat;">
			<% end %>
				
		<% end %>		
	<% end %>	
<% end %>

<script type="text/javascript">
	$('.show_more_btn').click(function(event){
		event.preventDefault();
		$(this).prev().show();
		$(this).hide();
	})
	$('.hide_desrcipt').click(function(event){
		event.preventDefault();
		$(this).parent().next().show();
		$(this).parent().hide();
	})
	function min_proj_list(a){
		$('a[bla = '+a+']').hide();
		$.ajax({
			method: 'get',
			url: '/list'
		}).done(function(response){
			a8 = response;
			for (var q = 0; q < a8.length; q++){
				if (jQuery.inArray(a, a8[q].developers_id) > 0){} else {
					$('a[bla = '+a+']').after('<a href="javascript:add_dev_to_proj('+a8[q].id+','+a+')" class="brr1" id2="'+a8[q].id+'"> --'+a8[q].title+'</a>');
				}
			}
		})
		$('a[bla = '+a+']').after('<a href="" id="brr_back"> | back </a>');
		$('#brr_back').click(function(event){
			event.preventDefault();
			$('.brr1').remove();
			$('#brr_back').remove();
			$('a[bla = '+a+']').show();
		})
	}
	function add_dev_to_proj(a,b){
		$.ajax({
			method: 'get',
			url: '/add_dev1',
			data: {'project_id': a, 'developer_id': b}
		}).done(function(response){
			$('a[id2 = '+a+']').remove();
		})
	}
	

</script>

app/views/developers/show.html.erb
<h1>Email: <%= @user.email %></h1>
<!-- <h1>Password: <%= @user.password %></h1> -->
<%= link_to "Edit", edit_user_path(@user) %> 

<h2>Projects</h2>
<table>
	<div class="col-md-12">
		<tr>
			<th>Project Title</th>
			<th>Decription</th>

		</tr>
	</div>
	<% @projects.each do |project| %>
		<tr>
			<td><%= link_to project.title, project.description %></td>
			<td><%= link_to "Cancel project", project, method: :delete %></td>
		</tr>
	<% end %>
</table>

app/views/developers/show2.js.erb
alert("wow");