config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do #change from clearance for mailer
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => 'welcome#index', as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  post "/developers/:id/show2" => "developers#show2"
  
  

  resources :projects do
    member do
      get "like", to: "projects#upvote"
      get "dislike", to: "projects#downvote"
    end
  end
  
  root 'welcome#index'
  resources :developers
  resources :projects
  post "/"    => "users#create"
  get '/list' => "projects#list"
  get '/list2' => "projects#list2"
  get 'projshow' => 'projects#show_proj'
  get "/add_dev" => 'projects#add_dev'
  get '/add_dev_leave' => 'projects#add_dev_leave'
  get '/show3' => 'developers#show3'
  get '/add_dev_leave1' => 'projects#add_dev_leave1'
  get "/add_dev1" => 'projects#add_dev1'
  

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
  	@users = User.all
	end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_form.html.erb
<!-- sign up form -->
<%= form_for :session, url: session_path do |form| %>
  <div class="text-field">
    <%= form.label :email %>
    <%= form.text_field :email, type: 'email' %>
  </div>

  <div class="password-field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <%= form.submit "Log In"%>
<% end %>

app/views/welcome/_form2.html.erb
<%= form_for :user, url: users_path do |form| %>
  <div class="text-field">
    <%= form.label :email %>
    <%= form.text_field :email, type: 'email' %>
  </div>

  <div class="password-field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <%= form.submit "Sign Up"%>
 <% end %>